# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "{Attila's Blog}"
email: uran198@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the blog about my journey in the programming world!
  Feel free to join a google group and subscribe to email updates to get an email every time I post.
  <a href='https://groups.google.com/forum/#!forum/uran198-blog/join'>Subscribe!</a>
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://uran198.github.io" # the base hostname & protocol for your site
twitter_username: ATovt
github_username:  Uran198
exclude: [about]

# Build settings
markdown: kramdown
